version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MOSQUITTO_URL=$MOSQUITTO_HOST:$MOSQUITTO_PORT
    ports:
      - ${API_PORT}:8000
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./log:/app/log
    depends_on:
      - database
    command: poetry run python -m src.main
    restart: always
  database:
    image: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always
  broker:
    image: eclipse-mosquitto
    env_file:
      - .env
    ports:
      - ${MOSQUITTO_PORT}:1883
    volumes:
      - ./mosquitto.conf/:/mosquitto/config/mosquitto.conf
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/certs:/mosquitto/certs
      - ./mosquitto/data:/mosquitto/data
    restart: always
