FROM ghcr.io/cirruslabs/flutter:3.16.0

RUN flutter precache

WORKDIR /app

COPY ./pubspec.yaml ./pubspec.lock ./
RUN flutter pub get

COPY ./android ./android
COPY ./lib ./lib
RUN flutter pub run build_runner build --delete-conflicting-outputs

RUN flutter build apk --release